remote_theme: CaptainIRS/hacker-plus-theme

title:
author:
description: 
disqus_forum_shortname:
google_site_verification_content: # The 'content' tag for site verification
google_analytics: # Your Google Analytics Tracking ID

# Usernames and badges
htb_badge_no: 335227
thm_badge_no: 85373
show_thm_htb_badges_in_nav: true
github_username: captshiva007
gitlab:
medium:
stackoverflow:
hacker_news:
linkedin: captshiva007
twitch:
youtube:
twitter: 
facebook:
instagram: aight_gtfo
reddit:
pinterest:
telegram:
steam:

# -------DO NOT ALTER -------#
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   notes:
      output: true
      permalink: /notes/:name/
   blog:
      output: true
